# Generated by Django 3.2.8 on 2022-02-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekoserver', '0002_alter_movies_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='backdrop_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdb_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
